version: "3.8"

services:
  go-mission-control:
    build:
      context: ./go-mission-control
      dockerfile: Dockerfile
    container_name: go-mission-control
    ports:
      - "8081:8081"
    depends_on:
      - greenctld
      - ait

  greenctld:
    build:
      context: ./greenctld
      dockerfile: Dockerfile
    container_name: greenctld
    ports:
      - "4533:4533"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - BAUD=9600

  gnuradio:
    build:
      context: ./gnuradio
      dockerfile: Dockerfile
    container_name: gnuradio

  ait:
    build:
      context: ./ait
      dockerfile: Dockerfile
    container_name: ait

  openmct:
    build:
      context: ./openmct
      dockerfile: Dockerfile
    container_name: openmct
    ports:
      - "8080:8080"
    depends_on:
      - go-mission-control

  gpredict:
    build:
      context: ./gpredict
      dockerfile: Dockerfile
    container_name: gpredict
    # If you need a GUI, handle that with VNC or X11
