# Dockerfile for go-mission-control
FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o mission-control main.go

EXPOSE 8081
CMD ["./mission-control"]
